apiVersion: v1
kind: Service
metadata:
  name: sentinel-service
  labels:
    app: sentinel-service
spec:
  ports:
    - port: 26379
      name: my-release2-redischart-sentinel
  clusterIp: None
  selector:
    app:  sentinel-service
---



apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-release2-redischart-sentinel
  namespace: "default"
  labels:
    app: redischart-sentinel

spec:
  replicas: 3
  serviceName: sentinel-service
  selector:
    matchLabels:
      app: redischart-sentinel

  template:
    metadata:
      labels:
        app: redischart-sentinel

    spec:
      securityContext:
        fsGroup: 1001
      serviceAccountName: default
      containers:
        - name: sentinel
          image: docker.io/bitnami/redis-sentinel:6.0.12-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command:
            - /bin/bash
            - -c
            - /opt/bitnami/scripts/start-scripts/start-sentinel.sh
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_SENTINEL_TLS_ENABLED
              value: "no"
            - name: REDIS_SENTINEL_PORT
              value: "26379"
          ports:
            - name: redis-sentinel
              containerPort: 26379
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_sentinel.sh 5
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_sentinel.sh 5
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /opt/bitnami/scripts/start-scripts/prestop-sentinel.sh
          resources:
            null
          volumeMounts:
            - name: start-scripts
              mountPath: /opt/bitnami/scripts/start-scripts
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
              subPath:
            - name: config
              mountPath: /opt/bitnami/redis-sentinel/mounted-etc
            - name: sentinel-tmp-conf
              mountPath: /opt/bitnami/redis-sentinel/etc
      volumes:
        - name: start-scripts
          configMap:
            name: my-release2-redischart-scripts
            defaultMode: 0755
        - name: health
          configMap:
            name: my-release2-redischart-health
            defaultMode: 0755
        - name: config
          configMap:
            name: my-release2-redischart
        - name: sentinel-tmp-conf
          emptyDir: {}
        - name: redis-tmp-conf
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app: redischart
          release: my-release2
          heritage: Helm
          component: slave
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "3Gi"

        selector:
  updateStrategy:
    type: RollingUpdate
