apiVersion: v1
kind: Service
metadata:
  name: my-release2-redischart-headless
  namespace: "default"
  labels:
    app: redischart
    release: my-release2
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redischart
    release: my-release2
