apiVersion: v1
kind: Service
metadata:
  name: my-release2-redischart
  namespace: "default"
  labels:
    app: redischart
    release: my-release2

spec:
  type: ClusterIP

  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app: redischart
    release: my-release2
