apiVersion: v1
kind: Service
metadata:
  name: my-release2-redischart
  namespace: "default"
  labels:
    app: redischart
    chart: redischart-0.1.0
    release: my-release2
    heritage: Helm
spec:
  type: ClusterIP

  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
    - name: tcp-sentinel
      port: 26379
      targetPort: redis-sentinel
  selector:
    app: redischart
    release: my-release2
